const data = [
  {
    name: "Giraffe",
    scientific_name: "Giraffa camelopardalis",
    type: "Mammal",
    habitat: "Savannah",
    diet: "Herbivore",
    fact: "Giraffes have the same number of neck vertebrae as humans, despite their long necks.",
    image: "./images/giraffe.jpg",
  },
  {
    name: "Elephant",
    scientific_name: "Loxodonta africana",
    type: "Mammal",
    habitat: "Savannah",
    diet: "Herbivore",
    fact: "Elephants have the largest brains of any land animal.",
    image: "./images/elephant.jpg",
  },
  {
    name: "Penguin",
    scientific_name: "Spheniscidae",
    type: "Bird",
    habitat: "Antarctica",
    diet: "Carnivore",
    fact: "Penguins can drink saltwater due to a special gland that filters the salt from their bloodstream.",
    image: "./images/penguin.jpg",
  },
  {
    name: "Orangutan",
    scientific_name: "Pongo pygmaeus",
    type: "Mammal",
    habitat: "Rainforest",
    diet: "Omnivore",
    fact: "Orangutans are the largest tree-dwelling animals in the world.",
    image: "./images/orangutan.jpg",
  },
  {
    name: "Kangaroo",
    scientific_name: "Macropus",
    type: "Mammal",
    habitat: "Australia",
    diet: "Herbivore",
    fact: "Kangaroos can jump up to three times their own body length in one bound.",
    image: "./images/kangaroo.jpg",
  },
  {
    name: "Octopus",
    scientific_name: "Octopoda",
    type: "Mollusk",
    habitat: "Ocean",
    diet: "Carnivore",
    fact: "Octopuses have three hearts and blue blood.",
    image: "./images/octopus.jpg",
  },
  {
    name: "Gorilla",
    scientific_name: "Gorilla beringei",
    type: "Mammal",
    habitat: "Rainforest",
    diet: "Herbivore",
    fact: "Gorillas can catch human colds and flu.",
    image: "./images/gorilla.jpg",
  },
  {
    name: "Sea Turtle",
    scientific_name: "Cheloniidae",
    type: "Reptile",
    habitat: "Ocean",
    diet: "Herbivore",
    fact: "Sea turtles have been around for over 110 million years, making them some of the oldest creatures on Earth.",
    image: "./images/turtle.jpg",
  },
  {
    name: "Lion",
    scientific_name: "Panthera leo",
    type: "Mammal",
    habitat: "Grasslands",
    diet: "Carnivore",
    fact: "Lions are the only cats that live in social groups, called prides.",
    image: "./images/lion.jpg",
  },
];

export default data;
